[tool.coverage.run]
parallel = true
branch = true
source = ["trv"]

[tool.coverage.paths]
source = ["src/trv", ".tox/*/site-packages/trv"]

[tool.coverage.report]
show_missing = true
skip_covered = true
